version: "3.2"
services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        environment:
            - TZ=America/Mexico_City
        networks:
            - apaching
        ports:
            - 9090:9090
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-admin-api
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        depends_on:
            - cadvisor
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        environment:
            - TZ=America/Mexico_City
        networks:
            - apaching
        ports:
            - 9089:8080        
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
    loki:
        image: grafana/loki:2.2.0
        container_name: loki
        environment:
            - TZ=America/Mexico_City
        networks:
            - apaching
        ports:
            - "9091:3100"
        command: 
            - --config.file=/etc/loki/local-config.yaml
        volumes:
            - './loki-config.yaml:/etc/loki/local-config.yaml'
    promtail:
        image: grafana/promtail:2.2.0
        container_name: promtail
        environment:
            - TZ=America/Mexico_City
        networks:
            - apaching
        volumes:
            - '/var/lib/docker/containers:/var/lib/docker/containers'
            - './promtail-config.yaml:/etc/promtail/config.yml'
        command: 
            - --config.file=/etc/promtail/config.yml            
    httpd01:
        image: httpd
        logging:
            driver: "json-file"
            options:
                tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
                max-size: 1g
        container_name: httpd_balanced_01
        environment:
            - TZ=America/Mexico_City        
        networks:
            apaching:
                ipv4_address: 172.50.0.11
        volumes:
            # server files
            - '${PWD}/httpd/htdocs:/usr/local/apache2/htdocs/'
            # Config files
            - '${PWD}/httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf'
            - '${PWD}/httpd/conf/extra/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf'
            - '${PWD}/httpd/conf/certs/team.angelbrv.com.cer:/usr/local/apache2/conf/server.cer'
            - '${PWD}/httpd/conf/certs/team.angelbrv.com.key:/usr/local/apache2/conf/server.key'
            - '${PWD}/httpd/conf/certs/fullchain.cer:/usr/local/apache2/conf/fullchain.cer'
        restart: unless-stopped
    httpd02:
        image: httpd
        logging:
            driver: "json-file"
            options:
                tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
                max-size: 1g
        container_name: httpd_balanced_02
        environment:
            - TZ=America/Mexico_City  
        networks:
            apaching:
                ipv4_address: 172.50.0.12
        volumes:
            # server files
            - '${PWD}/httpd/htdocs:/usr/local/apache2/htdocs/'
            # Config files
            - '${PWD}/httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf'
            - '${PWD}/httpd/conf/extra/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf'
            - '${PWD}/httpd/conf/certs/team.angelbrv.com.cer:/usr/local/apache2/conf/server.cer'
            - '${PWD}/httpd/conf/certs/team.angelbrv.com.key:/usr/local/apache2/conf/server.key'
            - '${PWD}/httpd/conf/certs/fullchain.cer:/usr/local/apache2/conf/fullchain.cer'
        restart: unless-stopped
    httpd03:
        image: httpd
        logging:
            driver: "json-file"
            options:
                tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
                max-size: 1g
        container_name: httpd_balanced_03        
        environment:
            - TZ=America/Mexico_City
        networks:
            apaching:
                ipv4_address: 172.50.0.13
        volumes:
            # server files
            - '${PWD}/httpd/htdocs:/usr/local/apache2/htdocs/'
            # Config files
            - '${PWD}/httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf'
            - '${PWD}/httpd/conf/extra/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf'
            - '${PWD}/httpd/conf/certs/team.angelbrv.com.cer:/usr/local/apache2/conf/server.cer'
            - '${PWD}/httpd/conf/certs/team.angelbrv.com.key:/usr/local/apache2/conf/server.key'
            - '${PWD}/httpd/conf/certs/fullchain.cer:/usr/local/apache2/conf/fullchain.cer'
        restart: unless-stopped
    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        logging:
            driver: "json-file"
            options:
                tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
                max-size: 1g
        container_name: php_service
        environment:
            - TZ=America/Mexico_City
        networks:
            apaching:
                ipv4_address: 172.50.0.21
        volumes:
            - '${PWD}/httpd/htdocs:/var/www/html'
            - './php/php.ini-production:/usr/local/etc/php/php.ini-production'
            - './php/php.ini-development:/usr/local/etc/php/php.ini-development'
            - './php/php.ini:/usr/local/etc/php/php.ini'
        restart: unless-stopped

networks:
    apaching:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.50.0.0/16

secrets:
    POSTGRES_PASSWORD:
        file: .secret_password_postgres.txt
